name: RustDesk CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  VCPKG_ROOT: C:\vcpkg
  VCPKG_BINARY_SOURCES: 'clear;x-gha,readwrite'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgDirectory: '${{ env.VCPKG_ROOT }}'
        vcpkgGitCommitId: '120deac3062162151622ca4860575a33844ba10b'

    - name: Install opus via vcpkg
      run: |
        & "$env:VCPKG_ROOT\vcpkg" install opus:x64-windows-static

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-pc-windows-msvc
        override: true

    - name: Build
      run: cargo build --release --verbose