name: Full Flutter CI

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Inject Config
        shell: bash
        run: python inject_secrets.py "\${{ secrets.MY_SERVER }}" "\${{ secrets.MY_KEY }}"
      - name: Build
        run: python build.py --flutter --release
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-windows
          path: target/release/rustdesk.exe
