name: Full Flutter CI

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
    - "docs/**"
    - "README.md"
  push:
    branches:
      - master
    paths-ignore:
      - ".github/**"
      - "docs/**"
      - "README.md"
      - "res/**"
      - "appimage/**"
      - "flatpak/**"

jobs:
  run-ci:
    # 这里调用了子脚本
    uses: ./.github/workflows/flutter-build.yml
    with:
      upload-artifact: false
    # 【新增：安全传递密钥】
    secrets:
      RS_ID_SERVER: ${{ secrets.RS_ID_SERVER }}
      RS_API_SERVER: ${{ secrets.RS_API_SERVER }}
      RS_PUB_KEY: ${{ secrets.RS_PUB_KEY }}